// Auto-generated by: npm run types:supabase
// Do not edit manually — run `npm run types:supabase` to regenerate after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      check_ins: {
        Row: {
          id: string
          user_id: string
          habit_id: string
          completed_at: string
          count: number
          created_at: string
          updated_at: string
          deleted_at: string | null
          version: number
        }
        Insert: {
          id?: string
          user_id: string
          habit_id: string
          completed_at: string
          count?: number
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
          version?: number
        }
        Update: {
          id?: string
          user_id?: string
          habit_id?: string
          completed_at?: string
          count?: number
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: 'check_ins_habit_id_fkey'
            columns: ['habit_id']
            isOneToOne: false
            referencedRelation: 'habits'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'check_ins_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      habits: {
        Row: {
          id: string
          user_id: string
          ritual_id: string
          name: string
          icon: string
          color: string
          target_per_day: number
          reminder_time: string | null
          position: number
          created_at: string
          updated_at: string
          deleted_at: string | null
          version: number
        }
        Insert: {
          id?: string
          user_id: string
          ritual_id: string
          name: string
          icon: string
          color: string
          target_per_day?: number
          reminder_time?: string | null
          position?: number
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
          version?: number
        }
        Update: {
          id?: string
          user_id?: string
          ritual_id?: string
          name?: string
          icon?: string
          color?: string
          target_per_day?: number
          reminder_time?: string | null
          position?: number
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: 'habits_ritual_id_fkey'
            columns: ['ritual_id']
            isOneToOne: false
            referencedRelation: 'rituals'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'habits_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      profiles: {
        Row: {
          id: string
          created_at: string
          display_name: string | null
          timezone: string
        }
        Insert: {
          id: string
          created_at?: string
          display_name?: string | null
          timezone?: string
        }
        Update: {
          id?: string
          created_at?: string
          display_name?: string | null
          timezone?: string
        }
        Relationships: [
          {
            foreignKeyName: 'profiles_id_fkey'
            columns: ['id']
            isOneToOne: true
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      rituals: {
        Row: {
          id: string
          user_id: string
          slug: string
          name: string
          position: number
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          slug: string
          name: string
          position?: number
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          slug?: string
          name?: string
          position?: number
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'rituals_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      sync_meta: {
        Row: {
          user_id: string
          last_pulled_at: string | null
          last_pushed_at: string | null
        }
        Insert: {
          user_id: string
          last_pulled_at?: string | null
          last_pushed_at?: string | null
        }
        Update: {
          user_id?: string
          last_pulled_at?: string | null
          last_pushed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'sync_meta_user_id_fkey'
            columns: ['user_id']
            isOneToOne: true
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

type PublicSchema = Database[Extract<keyof Database, 'public'>]

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema['Tables'] & PublicSchema['Views'])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions['schema']]['Tables'] &
        Database[PublicTableNameOrOptions['schema']]['Views'])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions['schema']]['Tables'] &
      Database[PublicTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema['Tables'] &
        PublicSchema['Views'])
    ? (PublicSchema['Tables'] &
        PublicSchema['Views'])[PublicTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema['Tables']
    ? PublicSchema['Tables'][PublicTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema['Tables']
    ? PublicSchema['Tables'][PublicTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof PublicSchema['Enums']
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions['schema']]['Enums'][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema['Enums']
    ? PublicSchema['Enums'][PublicEnumNameOrOptions]
    : never
